"""Regenerate app/static/vendor/pygments.css.

Pygments ships its colours as CSS you generate once and commit -- there's
no runtime cost and nothing to load from a CDN (which the strict
`style-src 'self'` CSP would block anyway). Run this after a Pygments
upgrade or a theme change:

    python scripts/gen_pygments_css.py

Two styles, one per colour scheme, each scoped so it only applies inside
`.highlight`/`.code-plain` and only in the matching theme -- mirroring how
app/static/style.css itself resolves light vs dark vs the explicit toggle.
"""

from __future__ import annotations

from pathlib import Path

from pygments.formatters import HtmlFormatter

OUT = Path(__file__).resolve().parents[1] / "app" / "static" / "vendor" / "pygments.css"

LIGHT_STYLE = "friendly"  # muted, good contrast on the cream --panel
DARK_STYLE = "stata-dark"  # calm, low-glare; reads on the warm dark --panel


def _block(selector: str, style: str) -> str:
    """Pygments emits the token rules already scoped to
    `<selector> .highlight ...`, but also a handful of unscoped extras
    (`pre { line-height }`, line-number styles) that would leak to every
    <pre> on the site. Keep only the scoped lines -- line height and the
    box are set once, by hand, in main()."""
    prefix = f"{selector} .highlight"
    raw = HtmlFormatter(style=style).get_style_defs(prefix)
    return "\n".join(line for line in raw.splitlines() if line.startswith(prefix))


def _indent(block: str) -> str:
    return "\n".join("  " + line for line in block.splitlines())


def main() -> None:
    light = _block(":root:not([data-theme='dark'])", LIGHT_STYLE)
    dark_system = _block(":root:not([data-theme='light'])", DARK_STYLE)
    dark_toggle = _block(":root[data-theme='dark']", DARK_STYLE)

    css = f"""/* GENERATED by scripts/gen_pygments_css.py -- do not edit by hand. */

.highlight, .code-plain {{
  overflow-x: auto;
  border-radius: 6px;
  padding: 0.75rem 0.9rem;
  font-size: 0.85rem;
  line-height: 1.5;
}}
.highlight pre, .code-plain {{ margin: 0; white-space: pre; }}

/* -- light -- */
{light}

/* -- dark (system default) -- */
@media (prefers-color-scheme: dark) {{
{_indent(dark_system)}
}}

/* -- dark (explicit toggle) -- */
{dark_toggle}
"""
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(css, encoding="utf-8")
    print(f"wrote {OUT} ({len(css)} bytes)")


if __name__ == "__main__":
    main()
