"""Server-side syntax highlighting.

Code shows up in three places -- fenced blocks in the mentor's markdown
replies, the code_snippet field on a practice question, and worked
examples in a lesson -- and until now all three rendered as flat
monospace. Pygments turns them into classed HTML spans; a single
stylesheet (static/vendor/pygments.css, generated by
scripts/gen_pygments_css.py) colours them, and it works with the strict
`style-src 'self'` CSP because the colours live in that file, not inline.

No JavaScript: the HTML arrives already highlighted. A language we don't
recognize, or a highlight that raises for any reason, falls back to a
plain escaped <pre> -- a code sample must never fail to render.
"""

from __future__ import annotations

from functools import lru_cache

from markupsafe import Markup, escape
from pygments import highlight as _pygments_highlight
from pygments.formatters import HtmlFormatter
from pygments.lexers import get_lexer_by_name, guess_lexer
from pygments.util import ClassNotFound

# nowrap=True emits just the token <span>s -- no <pre>, no <div>. We add
# `<pre class="highlight">` ourselves so the output always starts with
# `<pre`, which is what stops markdown-it from wrapping it in a second
# <pre><code> of its own. The stylesheet targets `.highlight`.
_FORMATTER = HtmlFormatter(nowrap=True)


def _plain(code: str) -> Markup:
    return Markup(f'<pre class="code-plain">{escape(code)}</pre>')


@lru_cache(maxsize=256)
def highlight_code(code: str, language: str = "") -> Markup:
    """`code` highlighted as `language`, as `<pre class="highlight">...`.
    Unknown or blank language: try to guess; if that fails, or highlighting
    raises, a plain escaped block -- a code sample must never fail to
    render. Cached: the same snippet is re-rendered on every page view."""
    code = code.rstrip("\n")
    if not code:
        return Markup("")

    lexer = None
    if language.strip():
        try:
            lexer = get_lexer_by_name(language.strip().lower())
        except ClassNotFound:
            lexer = None
    if lexer is None:
        try:
            lexer = guess_lexer(code)
        except ClassNotFound:
            return _plain(code)

    try:
        inner = _pygments_highlight(code, lexer, _FORMATTER)
    except Exception:
        return _plain(code)
    return Markup(f'<pre class="highlight">{inner}</pre>')


def _markdown_highlight(code: str, lang: str, _attrs: object) -> str:
    """markdown-it's `highlight` hook: (code, lang, attrs) -> html string,
    dropped in verbatim. Safe here because highlight_code only ever returns
    Pygments spans inside a <pre> or an escape()'d block -- never raw
    source. The leading `<pre` also signals markdown-it not to re-wrap it."""
    return str(highlight_code(code, lang or ""))
